
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anbudai_demo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/anbudai_demo"
      JWT_SECRET: "dev_jwt"
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data:
